name: Mega Downloader
on: 
  push:

defaults:
  run:
    shell: bash

env:
  LINK: https://mega.nz/file/fxtkgJ4C#PSWHWFcjdOtNFDkKcNYZUaQ-0Ffep6FNXwFmb0p_E74
  FILE_NAME: 
  UPLOAD: 

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo & checkout code
      uses: actions/checkout@v2

    - name: SSH agent
      uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
        key_file: frs.sourceforge.net

    - name: Download
      uses: Difegue/action-megacmd@master
      with:
        args: get ${LINK} $HOME

    - name: Upload..
      run: |
        echo next..
        cd $HOME && ls -al
