name: mirrorbot deploy

on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  deploy:
    name: bot mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Bot..
        run: |
          git config --global user.email jarbull86@gmail.com
          git config --global user.name NFS86
          git clone https://NFS86:$GH_TOKEN@github.com/NFS86/mirrorbot
          cd mirrorbot
          sudo docker build . -t mirrorbot
          sudo docker run -p 80:80 mirrorbot
      - name: Run Bot..
        run: |
          cd mirrorbot
          sudo docker run -p 80:80 mirrorbot
